update=2018/06/02 2:27:43
version=1
last_client=kicad
[general]
version=1
RootSch=
BoardNm=
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=M5_USB_Host_v01.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=../../MyLibrary/component
[eeschema/libraries]
LibName1=M5_USB_Host_v01-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=ADP3338AKCZ­3.3-RL
LibName32=cp210_mlp28
LibName33=sp0503bahtg_sot143-4n
LibName34=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName35=C:/Program Files/KiCad/share/kicad/library/74xx
LibName36=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName37=C:/Program Files/KiCad/share/kicad/library/actel
LibName38=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName39=C:/Program Files/KiCad/share/kicad/library/allegro
LibName40=C:/Program Files/KiCad/share/kicad/library/Altera
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName43=C:/Program Files/KiCad/share/kicad/library/atmel
LibName44=C:/Program Files/KiCad/share/kicad/library/audio
LibName45=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName46=C:/Program Files/KiCad/share/kicad/library/bbd
LibName47=C:/Program Files/KiCad/share/kicad/library/bosch
LibName48=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName49=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName50=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName51=C:/Program Files/KiCad/share/kicad/library/conn
LibName52=C:/Program Files/KiCad/share/kicad/library/contrib
LibName53=C:/Program Files/KiCad/share/kicad/library/cypress
LibName54=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName55=C:/Program Files/KiCad/share/kicad/library/device
LibName56=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName57=C:/Program Files/KiCad/share/kicad/library/diode
LibName58=C:/Program Files/KiCad/share/kicad/library/display
LibName59=C:/Program Files/KiCad/share/kicad/library/dsp
LibName60=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName61=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName62=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName63=C:/Program Files/KiCad/share/kicad/library/gennum
LibName64=C:/Program Files/KiCad/share/kicad/library/graphic
LibName65=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName66=C:/Program Files/KiCad/share/kicad/library/hc11
LibName67=C:/Program Files/KiCad/share/kicad/library/infineon
LibName68=C:/Program Files/KiCad/share/kicad/library/intel
LibName69=C:/Program Files/KiCad/share/kicad/library/interface
LibName70=C:/Program Files/KiCad/share/kicad/library/intersil
LibName71=C:/Program Files/KiCad/share/kicad/library/ir
LibName72=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName73=C:/Program Files/KiCad/share/kicad/library/leds
LibName74=C:/Program Files/KiCad/share/kicad/library/LEM
LibName75=C:/Program Files/KiCad/share/kicad/library/linear
LibName76=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName77=C:/Program Files/KiCad/share/kicad/library/logo
LibName78=C:/Program Files/KiCad/share/kicad/library/maxim
LibName79=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName80=C:/Program Files/KiCad/share/kicad/library/memory
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName83=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName85=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName86=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName87=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName88=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName89=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName90=C:/Program Files/KiCad/share/kicad/library/modules
LibName91=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName92=C:/Program Files/KiCad/share/kicad/library/motorola
LibName93=C:/Program Files/KiCad/share/kicad/library/motors
LibName94=C:/Program Files/KiCad/share/kicad/library/msp430
LibName95=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName96=C:/Program Files/KiCad/share/kicad/library/nxp
LibName97=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName98=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName99=C:/Program Files/KiCad/share/kicad/library/opto
LibName100=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName101=C:/Program Files/KiCad/share/kicad/library/philips
LibName102=C:/Program Files/KiCad/share/kicad/library/power
LibName103=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName104=C:/Program Files/KiCad/share/kicad/library/powerint
LibName105=C:/Program Files/KiCad/share/kicad/library/pspice
LibName106=C:/Program Files/KiCad/share/kicad/library/references
LibName107=C:/Program Files/KiCad/share/kicad/library/regul
LibName108=C:/Program Files/KiCad/share/kicad/library/relays
LibName109=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName110=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName111=C:/Program Files/KiCad/share/kicad/library/sensors
LibName112=C:/Program Files/KiCad/share/kicad/library/silabs
LibName113=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName114=C:/Program Files/KiCad/share/kicad/library/stm8
LibName115=C:/Program Files/KiCad/share/kicad/library/stm32
LibName116=C:/Program Files/KiCad/share/kicad/library/supertex
LibName117=C:/Program Files/KiCad/share/kicad/library/switches
LibName118=C:/Program Files/KiCad/share/kicad/library/texas
LibName119=C:/Program Files/KiCad/share/kicad/library/transf
LibName120=C:/Program Files/KiCad/share/kicad/library/transistors
LibName121=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName122=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName123=C:/Program Files/KiCad/share/kicad/library/valves
LibName124=C:/Program Files/KiCad/share/kicad/library/video
LibName125=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName126=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName127=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName128=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName129=C:/Program Files/KiCad/share/kicad/library/zetex
LibName130=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName131=MAX3421E
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
