update=2018/08/06 23:54:10
version=1
last_client=kicad
[general]
version=1
RootSch=
BoardNm=
[cvpcb]
version=1
NetIExt=net
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=M5_USB_Host_v03.net
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.2
BoardOutlineThickness=0.15
ModuleOutlineThickness=0.15
[eeschema]
version=1
LibDir=../../MyLibrary/component
[eeschema/libraries]
LibName1=sliede_sw_01
LibName2=M5_USB_Host_v03-rescue
LibName3=power
LibName4=device
LibName5=transistors
LibName6=conn
LibName7=linear
LibName8=regul
LibName9=74xx
LibName10=cmos4000
LibName11=adc-dac
LibName12=memory
LibName13=xilinx
LibName14=microcontrollers
LibName15=dsp
LibName16=microchip
LibName17=analog_switches
LibName18=motorola
LibName19=texas
LibName20=intel
LibName21=audio
LibName22=interface
LibName23=digital-audio
LibName24=philips
LibName25=display
LibName26=cypress
LibName27=siliconi
LibName28=opto
LibName29=atmel
LibName30=contrib
LibName31=valves
LibName32=ADP3338AKCZ­3.3-RL
LibName33=cp210_mlp28
LibName34=sp0503bahtg_sot143-4n
LibName35=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName36=C:/Program Files/KiCad/share/kicad/library/74xx
LibName37=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName38=C:/Program Files/KiCad/share/kicad/library/actel
LibName39=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName40=C:/Program Files/KiCad/share/kicad/library/allegro
LibName41=C:/Program Files/KiCad/share/kicad/library/Altera
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName43=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName44=C:/Program Files/KiCad/share/kicad/library/atmel
LibName45=C:/Program Files/KiCad/share/kicad/library/audio
LibName46=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName47=C:/Program Files/KiCad/share/kicad/library/bbd
LibName48=C:/Program Files/KiCad/share/kicad/library/bosch
LibName49=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName50=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName51=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName52=C:/Program Files/KiCad/share/kicad/library/conn
LibName53=C:/Program Files/KiCad/share/kicad/library/contrib
LibName54=C:/Program Files/KiCad/share/kicad/library/cypress
LibName55=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName56=C:/Program Files/KiCad/share/kicad/library/device
LibName57=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName58=C:/Program Files/KiCad/share/kicad/library/diode
LibName59=C:/Program Files/KiCad/share/kicad/library/display
LibName60=C:/Program Files/KiCad/share/kicad/library/dsp
LibName61=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName62=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName63=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName64=C:/Program Files/KiCad/share/kicad/library/gennum
LibName65=C:/Program Files/KiCad/share/kicad/library/graphic
LibName66=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName67=C:/Program Files/KiCad/share/kicad/library/hc11
LibName68=C:/Program Files/KiCad/share/kicad/library/infineon
LibName69=C:/Program Files/KiCad/share/kicad/library/intel
LibName70=C:/Program Files/KiCad/share/kicad/library/interface
LibName71=C:/Program Files/KiCad/share/kicad/library/intersil
LibName72=C:/Program Files/KiCad/share/kicad/library/ir
LibName73=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName74=C:/Program Files/KiCad/share/kicad/library/leds
LibName75=C:/Program Files/KiCad/share/kicad/library/LEM
LibName76=C:/Program Files/KiCad/share/kicad/library/linear
LibName77=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName78=C:/Program Files/KiCad/share/kicad/library/logo
LibName79=C:/Program Files/KiCad/share/kicad/library/maxim
LibName80=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName81=C:/Program Files/KiCad/share/kicad/library/memory
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip
LibName83=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName85=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName86=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName87=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName88=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName89=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName90=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName91=C:/Program Files/KiCad/share/kicad/library/modules
LibName92=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName93=C:/Program Files/KiCad/share/kicad/library/motorola
LibName94=C:/Program Files/KiCad/share/kicad/library/motors
LibName95=C:/Program Files/KiCad/share/kicad/library/msp430
LibName96=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName97=C:/Program Files/KiCad/share/kicad/library/nxp
LibName98=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName99=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName100=C:/Program Files/KiCad/share/kicad/library/opto
LibName101=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName102=C:/Program Files/KiCad/share/kicad/library/philips
LibName103=C:/Program Files/KiCad/share/kicad/library/power
LibName104=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName105=C:/Program Files/KiCad/share/kicad/library/powerint
LibName106=C:/Program Files/KiCad/share/kicad/library/pspice
LibName107=C:/Program Files/KiCad/share/kicad/library/references
LibName108=C:/Program Files/KiCad/share/kicad/library/regul
LibName109=C:/Program Files/KiCad/share/kicad/library/relays
LibName110=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName111=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName112=C:/Program Files/KiCad/share/kicad/library/sensors
LibName113=C:/Program Files/KiCad/share/kicad/library/silabs
LibName114=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName115=C:/Program Files/KiCad/share/kicad/library/stm8
LibName116=C:/Program Files/KiCad/share/kicad/library/stm32
LibName117=C:/Program Files/KiCad/share/kicad/library/supertex
LibName118=C:/Program Files/KiCad/share/kicad/library/switches
LibName119=C:/Program Files/KiCad/share/kicad/library/texas
LibName120=C:/Program Files/KiCad/share/kicad/library/transf
LibName121=C:/Program Files/KiCad/share/kicad/library/transistors
LibName122=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName123=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName124=C:/Program Files/KiCad/share/kicad/library/valves
LibName125=C:/Program Files/KiCad/share/kicad/library/video
LibName126=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName127=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName128=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName129=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName130=C:/Program Files/KiCad/share/kicad/library/zetex
LibName131=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName132=MAX3421E
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
